/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      height: { h1: "100vh", guestloginh1: "7vh" },
      width: { w1: "100vw", guestloginw1: "25.6vw" },
      spacing: {
        loginspacing1: "8vh",
        loginspacing2: "1.5vw",
        mainspacingt1: "10.2vh",
        mainspacingt2: "1vh",
        mainspacingt3: "12vh",
        mainspacingt4: "13vh",
        mainspacingt5: "4vh",
        mainspacingl1: "30vw",
        mainspacingl2: "4vw",
        mainspacingl3: "30vw",
        mainspacingl4: "22vw",
        mainspacingl5: "34vw",
      },
      colors: { "regal-blue": "#243c5a" },
      backgroundImage: {},
      fontSize: {
        xs: ".75rem",
        sm: ".875rem",
        tiny: ".875rem",
        base: "1rem",
        lg: "1.125rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
        "3xl": "1.875rem",
        "4xl": "2.25rem",
        "5xl": "3rem",
        "6xl": "4rem",
        "7xl": "5rem",

        maint1medium: "2rem",
        maint2medium: "2.8rem",
        maint3small: "1.5rem",
        maint4small: "2.2rem",
        maint5: "1.0rem",
        maint6: "1.7rem",
        main2xl1: "2.5rem",
        main2xl2: "3.47rem",
      },
    },
  },
  plugins: [],
};
